# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMax <- function(arr, n) {
    .Call(`_TriRadix_getMax`, arr, n)
}

countSort <- function(arr, n, exp) {
    invisible(.Call(`_TriRadix_countSort`, arr, n, exp))
}

radixsort <- function(arr) {
    .Call(`_TriRadix_radixsort`, arr)
}

get_digit <- function(num, d) {
    .Call(`_TriRadix_get_digit`, num, d)
}

counting_sort_by_digit <- function(arr, digit_position) {
    .Call(`_TriRadix_counting_sort_by_digit`, arr, digit_position)
}

radix_sort_rcpp <- function(arr) {
    .Call(`_TriRadix_radix_sort_rcpp`, arr)
}

